name: Link Check

on:
  push:
    branches:
      - main  # 仅在推送到 main 分支时触发
  pull_request:
    branches:
      - '*'

jobs:
  link-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.1  # 使用适当版本的 Ruby

      - name: Install dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build site with Jekyll
        run: bundle exec jekyll build

      - name: Check Links
        run: |
          bundle exec htmlproofer ./_site \
            --url-ignore "http://sobereva.com,http://bbs.keinsci.com" \
            --check-external-hash \
            --allow-hash-href
