name: Generate Posts Index

on:
  push:
    paths:
      - '_posts/**'
    branches:
      - main
      - master
  workflow_dispatch:

# 添加必要的权限
permissions:
  contents: write

jobs:
  generate-index:
    runs-on: ubuntu-latest
    concurrency:
      group: "post-index"
      cancel-in-progress: true
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'
    
    - name: Generate Posts Index
      run: |
        mkdir -p .github/scripts
        python .github/scripts/generate_index.py
    
    - name: Commit and Push Index
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --local user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add 1970-1-1-PostIndex.md
        git diff --quiet && git diff --staged --quiet || (git commit -m "Update posts index [skip ci]" && git push)